### ISSUE TITLE
Fix broken SDKMAN release

### ISSUE THREAD

**Issue by marc0der** [netdava/jbakery#1]
The current default version on SDKMAN is set to **0.0.4**, yet only **0.0.5-SNAPSHOT** was published. This results in broken downloads for people trying to install your tool. Furthermore, the URL pointing to the 0.0.5-SNAPSHOT distribution was a gzipped tarball, **not a zip**.

This needs to be rectified as soon as possible please, otherwise this candidate will be removed from SDKMAN.

**Comment by ieugen** [comment]
please remove it.
